name: LINT

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create environment
        shell: bash
        run: conda env create -f environment.yml -p ~/.env

      - name: PyLint
        shell: bash
        run: ~/.env/bin/pylint httpfs/
