name: TEST

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create environment
        shell: bash
        run: conda env create -f environment.yml -p ~/.env

      - name: PyTest
        shell: bash
        run: ~/.env/bin/pytest --cov=httpfs tests/
